### PR TITLE
[WIP] Feature: events

### PR DESCRIPTION
**Pull request by rmcfadzean**
WIP

Related to #28 & #38

### CODE REVIEW

**Comment by JacobMGEvans** [comment]
I see ya'll change the file and directory naming convention back...

**Comment by JacobMGEvans** [comment]
Current fail on check deploy preview
```sh
2:31:08 PM: Installing NPM modules using Yarn version 1.17.0
2:31:09 PM: yarn install v1.17.0
2:31:09 PM: [1/4] Resolving packages...
2:31:10 PM: [2/4] Fetching packages...
2:31:46 PM: info fsevents@2.1.1: The platform "linux" is incompatible with this module.
2:31:46 PM: info "fsevents@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
2:31:46 PM: info fsevents@1.2.9: The platform "linux" is incompatible with this module.
2:31:46 PM: info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
2:31:46 PM: [3/4] Linking dependencies...
2:31:46 PM: warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
2:32:02 PM: [4/4] Building fresh packages...
2:32:08 PM: Done in 58.73s.
2:32:08 PM: NPM modules installed using Yarn
2:32:08 PM: Started restoring cached go cache
2:32:08 PM: Finished restoring cached go cache
2:32:08 PM: unset GOOS;
2:32:08 PM: unset GOARCH;
2:32:08 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
2:32:08 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
2:32:08 PM: go version >&2;
2:32:08 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
2:32:08 PM: go version go1.12 linux/amd64
2:32:08 PM: Installing missing commands
2:32:08 PM: Verify run directory
2:32:08 PM: Executing user command: gatsby build
2:32:11 PM: success open and validate gatsby-configs - 0.032s
2:32:12 PM: success load plugins - 1.023s
2:32:12 PM: success onPreInit - 0.003s
2:32:12 PM: success delete html and css files from previous builds - 0.016s
2:32:12 PM: success initialize cache - 0.010s
2:32:12 PM: success copy gatsby files - 0.055s
2:32:12 PM: success onPreBootstrap - 0.012s
2:32:13 PM: success source and transform nodes - 0.290s
2:32:13 PM: success building schema - 0.550s
2:32:13 PM: error There was an error in your GraphQL query:
2:32:13 PM: Field "fields" is not defined by type MarkdownRemarkFilterInput.
2:32:13 PM: error There was an error in your GraphQL query:
2:32:13 PM: Expected type MarkdownRemarkFieldsEnum, found frontmatter___startDate.
2:32:13 PM: error There was an error in your GraphQL query:
2:32:13 PM: Cannot query field "fields" on type "MarkdownRemark".
2:32:13 PM: error There was an error in your GraphQL query:
2:32:13 PM: Cannot query field "frontmatter" on type "MarkdownRemark".
2:32:14 PM: not finished createPages - 0.215s
2:32:14 PM: Skipping functions preparation step: no functions directory set
2:32:14 PM: Caching artifacts
2:32:14 PM: Started saving node modules
2:32:14 PM: Finished saving node modules
2:32:14 PM: Started saving yarn cache
2:32:14 PM: Finished saving yarn cache
2:32:14 PM: Started saving pip cache
2:32:14 PM: Finished saving pip cache
2:32:14 PM: Started saving emacs cask dependencies
2:32:14 PM: Finished saving emacs cask dependencies
2:32:14 PM: Started saving maven dependencies
2:32:14 PM: Finished saving maven dependencies
2:32:14 PM: Started saving boot dependencies
2:32:14 PM: Finished saving boot dependencies
2:32:14 PM: Started saving go dependencies
2:32:14 PM: Finished saving go dependencies
2:32:20 PM: Error running command: Build script returned non-zero exit code: 1
2:32:20 PM: Failing build: Failed to build site
2:32:20 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
2:32:20 PM: Finished processing build request in 1m41.487410638s
```

**Comment by rmcfadzean** [comment]
Known issue as there are currently no events. Got some work deadlines coming up but I'll get back on this ASAP.

**Comment by rmcfadzean** [comment]
As for filenames, the general rule is to use PascalCase for components and their file names.

**Comment by JacobMGEvans** [comment]
> As for filenames, the general rule is to use PascalCase for components and their file names.

That's a personal preference from my perspective there isn't even really an industry-standard the 3 companies I've worked for in the last 2 years all did it differently... That bikeshedding aside I am fine with it as long as it compiles 😆😅

**Comment by JacobMGEvans** [comment]
> Known issue as there are currently no events. Got some work deadlines coming up but I'll get back on this ASAP.

Take your time of course :) All your effort and work are very much appreciated!! Work work definitely is the priority. Again I greatly appreciate your personal time you choose to use here.

**Comment by rmcfadzean** [comment]
I am by no means a designer so styling is... non existent. I'll get @blindingstars in on that when she has time. 

The build should no longer be failing and instead just lacking events.

**Comment by JacobMGEvans** [comment]
> I am by no means a designer so styling is... non-existent. I'll get @blindingstars in on that when she has time.
> 
> The build should no longer be failing and instead just lacking events.

I usually am doing some serious copypasta for design so I feel that for sure 🤣

**Pull request merged**
